export const TOP_DISCOVERY_LINKS = [
  {
    href: '/guides',
    label: 'قسم الأدلة العملية',
    description: 'بوابة تجمع المقالات الشارحة مع روابط مباشرة إلى الحاسبات وأدوات الاقتصاد والمسارات اليومية.',
  },
  {
    href: '/calculators/sleep',
    label: 'حاسبات النوم الذكي',
    description: 'بوابة تجمع متى تنام ومتى تستيقظ والقيلولة ودين النوم في نظام واحد.',
  },
  {
    href: '/calculators/sleep/bedtime',
    label: 'متى أنام لأستيقظ في الوقت المناسب؟',
    description: 'احصل على أوقات النوم المقترحة حسب دورات النوم ووقت الغفو التقريبي.',
  },
  {
    href: '/calculators/sleep/wake-time',
    label: 'إذا نمت الآن، متى أستيقظ؟',
    description: 'أداة فورية وعالية الاستخدام تبني وقت الاستيقاظ من لحظة النوم الحالية.',
  },
  {
    href: '/calculators/personal-finance',
    label: 'حاسبات التخطيط المالي الشخصي',
    description: 'بوابة تجمع صندوق الطوارئ والديون والادخار وصافي الثروة في مسار واحد.',
  },
  {
    href: '/calculators/personal-finance/emergency-fund',
    label: 'كم تحتاج صندوق طوارئ؟',
    description: 'احسب صندوق الطوارئ المناسب لك واعرف المبلغ المتبقي والمدة المتوقعة للوصول.',
  },
  {
    href: '/calculators/personal-finance/debt-payoff',
    label: 'متى أخلص من ديوني؟',
    description: 'احسب مدة سداد الديون وقارن بين كرة الثلج والانهيار.',
  },
  {
    href: '/economie/market-hours',
    label: 'ساعات الأسواق والتداول',
    description: 'مسار يجمع السوق الأمريكي والذهب والفوركس والبورصات العالمية في مكان واحد.',
  },
  {
    href: '/calculators/finance',
    label: 'حاسبات المال والعمل',
    description: 'بوابة تجمع القسط والضريبة والنسبة المئوية ومكافأة نهاية الخدمة في مكان واحد.',
  },
  {
    href: '/calculators/age/calculator',
    label: 'كم عمري الآن؟ حاسبة العمر',
    description: 'احسب عمرك بالسنوات والأشهر والأيام والثواني مع عيد الميلاد القادم وكم يوم عشت.',
  },
  {
    href: '/calculators/monthly-installment',
    label: 'كم قسط القرض الشهري؟',
    description: 'اعرف القسط الشهري وإجمالي الفوائد وأثر السداد المبكر قبل اتخاذ قرار التمويل.',
  },
  {
    href: '/calculators/vat',
    label: 'كم الضريبة 15%؟',
    description: 'أضف ضريبة القيمة المضافة أو استخرجها من السعر الشامل فوراً وبشكل واضح.',
  },
  {
    href: '/guides/how-to-compare-loan-offers',
    label: 'كيف تقارن عروض القروض دون أن تنخدع بالقسط الأقل؟',
    description: 'دليل يشرح المقارنة بين القسط والإجمالي والرسوم قبل اختيار التمويل.',
  },
  {
    href: '/economie/us-market-open',
    label: 'متى يفتح السوق الأمريكي اليوم؟',
    description: 'اعرف وقت الافتتاح بتوقيتك المحلي مع عد تنازلي مباشر وجدول للدول العربية.',
  },
  {
    href: '/economie/gold-market-hours',
    label: 'هل الذهب مفتوح الآن؟',
    description: 'تحقق فوراً من حالة سوق الذهب وساعات التداول الحالية وروابط الأدوات الاقتصادية المرتبطة.',
  },
  {
    href: '/guides/what-are-forex-sessions',
    label: 'ما هي جلسات الفوركس؟ وكيف تفهم لندن ونيويورك',
    description: 'دليل يشرح الجلسات والتداخل والسيولة بلغة عربية مباشرة قبل استخدام الأداة الحية.',
  },
];

export const ROOT_PRIORITY_TOOL_PATHS = [
  '/fahras',
  '/guides',
  '/calculators/sleep',
  '/calculators/sleep/bedtime',
  '/calculators/sleep/wake-time',
  '/calculators/sleep/sleep-duration',
  '/calculators/sleep/nap-calculator',
  '/calculators/sleep/sleep-debt',
  '/calculators/sleep/sleep-needs-by-age',
  '/calculators/personal-finance',
  '/calculators/personal-finance/emergency-fund',
  '/calculators/personal-finance/debt-payoff',
  '/calculators/personal-finance/savings-goal',
  '/calculators/personal-finance/net-worth',
  '/calculators/finance',
  '/calculators/age',
  '/calculators/age/calculator',
  '/calculators/age/hijri',
  '/calculators/age/difference',
  '/calculators/age/milestones',
  '/calculators/building',
  '/calculators/building/cement',
  '/calculators/building/rebar',
  '/calculators/building/tiles',
  '/calculators/end-of-service-benefits',
  '/calculators/monthly-installment',
  '/calculators/vat',
  '/calculators/percentage',
  '/economie',
  '/economie/market-hours',
  '/economie/us-market-open',
  '/economie/gold-market-hours',
  '/economie/forex-sessions',
  '/economie/stock-markets',
  '/economie/market-clock',
  '/economie/best-trading-time',
  '/date/converter',
  '/date/today/hijri',
  '/date/today/gregorian',
  '/guides/emergency-fund',
  '/guides/how-to-compare-loan-offers',
  '/guides/fixed-vs-reducing-loan-rate',
  '/guides/vat-inclusive-vs-exclusive-price',
  '/guides/what-is-vat-input-vs-output-tax',
  '/guides/how-to-calculate-percentage-discount',
  '/guides/percentage-change-vs-percentage-points',
  '/guides/how-many-cement-bags-do-i-need',
  '/guides/how-to-estimate-rebar-weight',
  '/guides/end-of-service-benefits-saudi',
  '/guides/resignation-vs-contract-end-gratuity',
  '/guides/what-is-a-sleep-cycle',
  '/guides/how-many-hours-of-sleep-do-i-need',
  '/guides/best-nap-length',
  '/guides/sleep-debt-explained',
  '/guides/why-am-i-tired-after-sleeping',
  '/guides/how-long-does-it-take-to-fall-asleep',
  '/guides/rem-vs-deep-sleep',
  '/guides/sleep-hygiene-basics',
  '/guides/when-does-us-market-open',
  '/guides/what-are-forex-sessions',
  '/guides/best-time-to-trade-gold',
  '/guides/how-to-read-market-clock',
  '/guides/debt-payoff-methods',
  '/guides/how-much-save-monthly',
  '/guides/net-worth-explained',
  '/guides/how-many-months-emergency-fund',
  '/guides/how-to-pay-off-debt-fast',
  '/guides/save-for-goal',
  '/guides/assets-vs-liabilities',
];

export function appendToolDiscoveryLinks(baseLinks = []) {
  const merged = [...baseLinks, ...TOP_DISCOVERY_LINKS];
  const seen = new Set();

  return merged.filter((link) => {
    if (!link?.href || seen.has(link.href)) return false;
    seen.add(link.href);
    return true;
  });
}
