# syntax=docker/dockerfile:1.7

FROM node:20-bookworm-slim AS base

ENV NEXT_TELEMETRY_DISABLED=1
WORKDIR /app

RUN apt-get update \
 && apt-get install -y --no-install-recommends openssl ca-certificates \
 && rm -rf /var/lib/apt/lists/*

FROM base AS deps

COPY package.json package-lock.json ./
RUN --mount=type=cache,target=/root/.npm npm ci

FROM base AS builder

ARG NEXT_OUTPUT_MODE=standalone
ARG NEXT_PUBLIC_SITE_URL
ARG NEXT_PUBLIC_BASE_URL
ARG VERCEL_PROJECT_PRODUCTION_URL
ARG VERCEL_URL
ARG GOOGLE_SITE_VERIFICATION
ARG ENABLE_LIVE_GEO_DB
ARG LIVE_GEO_PROVIDER
ARG NEXT_PUBLIC_ENABLE_ANALYTICS
ARG NEXT_PUBLIC_GA_MEASUREMENT_ID
ARG NEXT_PUBLIC_GTM_ID
ARG NEXT_PUBLIC_ENABLE_ADS
ARG NEXT_PUBLIC_ADSENSE_CLIENT_ID
ARG NEXT_PUBLIC_ADSENSE_TOP_BANNER_SLOT
ARG NEXT_PUBLIC_ADSENSE_STICKY_ANCHOR_SLOT
ARG NEXT_PUBLIC_ADSENSE_IN_ARTICLE_SLOT
ARG NEXT_PUBLIC_ADSENSE_SIDEBAR_SLOT
ARG NEXT_PUBLIC_ADSENSE_SIDEBAR_LEFT_SLOT
ARG NEXT_PUBLIC_ADSENSE_SIDEBAR_RIGHT_SLOT
ARG NEXT_PUBLIC_ENABLE_CONSENT_BANNER
ARG NEXT_PUBLIC_ENABLE_SW
ARG NEXT_PUBLIC_SUPABASE_URL
ARG NEXT_PUBLIC_SUPABASE_ANON_KEY
ENV NODE_ENV=production \
    NEXT_OUTPUT_MODE=${NEXT_OUTPUT_MODE} \
    NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL} \
    NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL} \
    VERCEL_PROJECT_PRODUCTION_URL=${VERCEL_PROJECT_PRODUCTION_URL} \
    VERCEL_URL=${VERCEL_URL} \
    GOOGLE_SITE_VERIFICATION=${GOOGLE_SITE_VERIFICATION} \
    ENABLE_LIVE_GEO_DB=${ENABLE_LIVE_GEO_DB} \
    LIVE_GEO_PROVIDER=${LIVE_GEO_PROVIDER} \
    NEXT_PUBLIC_ENABLE_ANALYTICS=${NEXT_PUBLIC_ENABLE_ANALYTICS} \
    NEXT_PUBLIC_GA_MEASUREMENT_ID=${NEXT_PUBLIC_GA_MEASUREMENT_ID} \
    NEXT_PUBLIC_GTM_ID=${NEXT_PUBLIC_GTM_ID} \
    NEXT_PUBLIC_ENABLE_ADS=${NEXT_PUBLIC_ENABLE_ADS} \
    NEXT_PUBLIC_ADSENSE_CLIENT_ID=${NEXT_PUBLIC_ADSENSE_CLIENT_ID} \
    NEXT_PUBLIC_ADSENSE_TOP_BANNER_SLOT=${NEXT_PUBLIC_ADSENSE_TOP_BANNER_SLOT} \
    NEXT_PUBLIC_ADSENSE_STICKY_ANCHOR_SLOT=${NEXT_PUBLIC_ADSENSE_STICKY_ANCHOR_SLOT} \
    NEXT_PUBLIC_ADSENSE_IN_ARTICLE_SLOT=${NEXT_PUBLIC_ADSENSE_IN_ARTICLE_SLOT} \
    NEXT_PUBLIC_ADSENSE_SIDEBAR_SLOT=${NEXT_PUBLIC_ADSENSE_SIDEBAR_SLOT} \
    NEXT_PUBLIC_ADSENSE_SIDEBAR_LEFT_SLOT=${NEXT_PUBLIC_ADSENSE_SIDEBAR_LEFT_SLOT} \
    NEXT_PUBLIC_ADSENSE_SIDEBAR_RIGHT_SLOT=${NEXT_PUBLIC_ADSENSE_SIDEBAR_RIGHT_SLOT} \
    NEXT_PUBLIC_ENABLE_CONSENT_BANNER=${NEXT_PUBLIC_ENABLE_CONSENT_BANNER} \
    NEXT_PUBLIC_ENABLE_SW=${NEXT_PUBLIC_ENABLE_SW} \
    NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL} \
    NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}

COPY --from=deps /app/node_modules ./node_modules
COPY . .

RUN npm run build

FROM base AS runner

ENV NODE_ENV=production \
    NEXT_TELEMETRY_DISABLED=1 \
    HOSTNAME=0.0.0.0 \
    PORT=3000

WORKDIR /app

RUN groupadd --system --gid 1001 nodejs \
 && useradd --system --uid 1001 --gid nodejs nextjs \
 && mkdir -p /app/.next/cache \
 && chown -R nextjs:nodejs /app

COPY --from=builder --chown=nextjs:nodejs /app/public ./public
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000

HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=5 \
  CMD node -e "fetch('http://127.0.0.1:3000/api/health').then((res)=>{if(!res.ok)process.exit(1)}).catch(()=>process.exit(1))"

CMD ["node", "server.js"]
