CREATE EXTENSION IF NOT EXISTS pg_trgm;

CREATE TABLE IF NOT EXISTS public.countries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code CHAR(2) NOT NULL UNIQUE,
  country_slug TEXT NOT NULL UNIQUE,
  name_en TEXT,
  name_ar TEXT NOT NULL,
  timezone TEXT
);

CREATE TABLE IF NOT EXISTS public.cities (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  country_code CHAR(2) NOT NULL,
  city_slug TEXT NOT NULL,
  name_en TEXT,
  name_ar TEXT NOT NULL,
  lat DOUBLE PRECISION NOT NULL,
  lon DOUBLE PRECISION NOT NULL,
  timezone TEXT NOT NULL,
  population INTEGER DEFAULT 0,
  priority INTEGER DEFAULT 0,
  is_capital BOOLEAN DEFAULT FALSE,
  CONSTRAINT cities_country_code_fkey
    FOREIGN KEY (country_code)
    REFERENCES public.countries(country_code)
    ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_city_country
  ON public.cities (country_code);

CREATE INDEX IF NOT EXISTS idx_city_name_ar
  ON public.cities (name_ar text_pattern_ops);

CREATE INDEX IF NOT EXISTS idx_city_name_ar_trgm
  ON public.cities
  USING GIN (name_ar gin_trgm_ops);

CREATE INDEX IF NOT EXISTS idx_city_population
  ON public.cities (population DESC);
